### ISSUE TITLE
Typing is especially sluggish

### ISSUE THREAD

**Issue by ryw** [Differential/supporter#54]
In both "new issue" box + "response" box.

Seems to be only an issue in production.

**Comment by ryw** [comment]
This is caused by rerendering on each keypress. Meteor UI should fix this.

**Comment by hellogerard** [comment]
debounce function?

**Comment by ryw** [comment]
I didn't know of debounce — trying to get it working, it works good to start, but then after typing it doesn't seem to block the callback like it should :( Any experience with it in Meteor? Have a look @ the code if you get a sec...

**Comment by ryw** [comment]
Fixed
