### ISSUE TITLE
Requested Features :)

### ISSUE THREAD

**Issue by dovrosenberg** [Differential/supporter#61]
For GCVA use, it would be awesome to add 3 features that all tie together:

1) Ability to tag cards (arbitrary tags)
2) Expanded search by both text and tags (that is, specify search criteria separately for text and for tags... important for #3)
3) Ability to follow comments on cards by email.  Ideally this would work as follows:
     - I can subscribe to a card or I can subscribe to a search
     - I then get an email (sort of like yammer) detailing any comments, etc. to that card, or in the case of a search any comments to cards (or creation of new cards) that satisfy the search criteria.  This is why separating search by text and tag is important.  I may want to subscribe to see any new cards tagged "fundraising", but not to anything that just happens to have that word in it somewhere.

**Comment by ryw** [comment]
all of this is now coded up — need to test and find bugs :)

**Comment by dovrosenberg** [comment]
Awesome.  We’ll play around with it.

```
 - Dov
```
