### ISSUE TITLE
Default/Sign in Post

### ISSUE THREAD

**Issue by tmetzner** [Differential/supporter#70]
Copy for the default post explaining what to do and get people to register/signin:

Share your thoughts about how the Cincinnati startup community could be improved. Sign up or Sign in to post! 

We're looking for feedback for a specific organizations (i.e. It would be really helpful if Cintrifuse offered XZY) and more general (i.e. we really need more technical talent). 

Few quick notes:
1. The more specific your thoughts/feedback, the more helpful it will be.
2. If you're offering feedback, make it constructive (in other words, don't just tell us about a problem, suggest a way to fix it).
3. We will share your feedback with relevant organizations in town (they've agreed to listen to us as "the voice of the entrepreneurs) but we will keep your name anonymous (we will know who the feedback is coming from, we just won't pass that along unless you ask us to).

Sign in or sign up to post your feedback.

**Comment by spencercarli** [comment]
Closed via 778d36f37f198fec0aa0ebf03d4911c92b09cb2f
