### ISSUE TITLE
Create User Roles

### ISSUE THREAD

**Issue by tmetzner** [Differential/supporter#71]
We need the Cincinnati Entrepreneur Board to be able to login and see all the feedback submitted (basically the default public view at http://support.unpolishedcr.com/. 

We could either:
- create a special page to send our members (only about 10)
- have them all register for an account once the site is up and I'll have you manually "upgrade" them to admin role

**Comment by spencercarli** [comment]
via 4d8bae40dfd14509500d4f6f385692d6038ab028
