### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by tmetzner** [Differential/supporter#72]
Create a page that describes the Cincinnati Entrepreneur Board: who we are and what our goal is.

**Comment by spencercarli** [comment]
@tmetzner Do you have the copy for this page?

**Comment by tmetzner** [comment]
@spencercarli Jeff was going to, so I'll check back w/ him.

**Comment by tmetzner** [comment]
@spencercarli here's starter copy:

The Cincinnati Entrepreneur Board was created to be the voice of founders in the ecosystem. We're building an entrepreneur led culture by being a conduit between startups and the organizations serving the community. We help identify and initiate needed change. 

The Board is self-organizing, inclusive, and operates independently of the ecosystem organizations (but has the ear of all the key players). We meet monthly to synthesize feedback, prioritize needs, and move special projects forward (either independently of or in partnership with other organizations).

**Comment by spencercarli** [comment]
Closed via 9763fa624cf933d73792edad581b61e23ed110fd
